#!/bin/sh

VAGRANTHOME="/home/matty/vagrant"
KUBERNETES_NODE_COUNT=3

if [ $# -eq 1 ]; then
    KUBERNETES_BINARIES="kubeadm-${1} kubelet-${1} kubectl-${1}"
else
    KUBERNETES_BINARIES="kubeadm kubelet kubectl"
fi 

if [ ! -d ${VAGRANTHOME} ]; then
    echo "Creating a directory to store our vagrant boxes"
    mkdir ${VAGRANTHOME}
fi

for i in $(seq 1 ${KUBERNETES_NODE_COUNT}); do

echo "Creating a directory for Kubernetes node ${i}"
mkdir ${VAGRANTHOME}/kubeadm${i}

echo "Creating a node bootstrap file"
cat > ${VAGRANTHOME}/kubeadm${i}/bootstrap.sh << EOF
#!/bin/bash

echo "\$(hostname -I | tr ' ' '\n' | awk '/10.10.10/ {print}')  \$(/bin/hostname)" >> /etc/hosts
yum -y update
yum -y install docker
systemctl enable docker && systemctl start docker

echo "[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" > /etc/yum.repos.d/kubernetes.repo

echo "net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1" > /etc/sysctl.d/S10kubernetes
sysctl -p

sed -i 's/SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
setenforce permissive

dnf -y install ${KUBERNETES_BINARIES}
EOF

echo "Creating a Vagrantfile for Kubernetes node ${i}"
cat > ${VAGRANTHOME}/kubeadm${i}/Vagrantfile <<EOF
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/27-cloud-base"
  config.vm.hostname = "kub${i}"
  config.vm.network "private_network", ip: "10.10.10.$(( 100 + ${i}))"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end
EOF
echo "Starting the VM for vagrant box kubeadm${i}"
(cd ${VAGRANTHOME}/kubeadm${i} && vagrant up --provider=virtualbox &)
done
